### ISSUE TITLE
I can not train

### ISSUE THREAD

**Issue by sounansu** [huaifeng1993/DFANet#11]
I change main.py
`    net = dfanet(pretrained=True,num_classes=20)`
to
`    net = dfanet(pretrained=False,num_classes=20)`
and run.

    (DFANet) sounnansu@ubuntu2:~/anaconda3/DFANet$ python main.py
    ./log/dfanet20190805T1416
    Traceback (most recent call last):
      File "main.py", line 44, in <module>
        trainer.load_weights(trainer.find_last())
      File "/home/sounansu/anaconda3/DFANet/train.py", line 185, in find_last
        "Could not find weight files in {}".format(dir_name))
    FileNotFoundError: [Errno 2] Could not find weight files in  ./log/dfanet20190805T1416

**Comment by huaifeng1993** [comment]
If you train the model form 0 epoch you should delete the code --trainer.load_weights(trainer.find_last())

**Comment by sounansu** [comment]
Thank you!
I comment out 'trainer.load_weights(trainer.find_last())'.

There are no errors!

I changed some operation at
[Dataset and pretrained model](https://github.com/huaifeng1993/DFANet#dataset-and-pretrained-model) .

> Then run the command 'python utils/preprocess.py' to create labels.
I used preprocess_data.py instead of preprocess.py.

Is is correct?

**Comment by huaifeng1993** [comment]
Thank you for pointing out the mistake.!!
